# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://samutsarihub.com/
title: SamutSaring Bahay at Lupa
email: larrysuico2@gmail.com
author: Larry Suico
description: The goal of this site is the help you find your Dream Home or Property Investment 
  #You can edit this line in _config.yml. It will appear in your document 
  #head meta (for Google search results) and in your feed.xml site 
  #description.
copyright: 'Copyright &copy; 2017 SamutSariHub. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#social:
  #- title: Facebook
    #url: https://www.facebook.com/samutsarihub/
  
